program: sweep.sh
method: bayes
metric: 
  name: train/.loss_all_scaled
  goal: minimize
parameters:
  vl_enc_layers:
    values: [4, 6]
  obj_dec_layers:
    values: [4, 6]
  lang_dec_layers:
    values: [4, 6]
  dim_feedforward:
    values: [1024, 2048]
  hidden_dim:
    values: [256, 512]
  epochs:
    value: 1
command:
  - ${env}
  - bash
  - ${program}
  - ${args}